version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idea_board_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./idea_board_backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: 8000
      DATABASE_URL: "postgres://postgres:postgres@db:5432/idea_board_db"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./idea_board_frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://backend:8000"
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
